/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.server;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.net.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author HuyBao
 */
public class Server extends javax.swing.JFrame {

//    private final DefaultTableModel logModel;
//    private final DefaultListModel listModel = new DefaultListModel();
    public static Socket socket = null;
    private final int PORT = 9999;
    public static String pathDirectory = "";
    public static DefaultListModel<String> listModel = new DefaultListModel<>();
    public static ArrayList<Socket> listSocketClient = new ArrayList<>();
    public static ArrayList<String> listNameClient = new ArrayList<>();
    public static HashMap<Socket, ArrayList<String>> Log_Socket = new HashMap<>();
    public static HashMap<String, Socket> Name_Socket = new HashMap<>();

    /**
     * Creates new form Server
     */
    public Server() {
        initComponents();
        edtPath.setText(pathDirectory);
        jListName.setModel(listModel);
        JTableHeader header = tableLogs.getTableHeader();
        header.setForeground(Color.darkGray);
        header.setFont(new Font("Segoe UI", Font.BOLD, 14));
        edtPath.setText("Choose a directory path");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLogs = new javax.swing.JTable();
        btnStart = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        addressServer = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        valuePort = new javax.swing.JLabel();
        edtPath = new javax.swing.JTextField();
        btnBrowser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListName = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        valueHost = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setPreferredSize(new java.awt.Dimension(970, 630));

        tableLogs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Date", "ID Machine", "Log", "Path", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLogs.setRowHeight(25);
        tableLogs.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableLogs);
        if (tableLogs.getColumnModel().getColumnCount() > 0) {
            tableLogs.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableLogs.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableLogs.getColumnModel().getColumn(2).setPreferredWidth(80);
            tableLogs.getColumnModel().getColumn(3).setPreferredWidth(300);
            tableLogs.getColumnModel().getColumn(4).setPreferredWidth(100);
            tableLogs.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        btnStart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStart.setText("Start");
        btnStart.setPreferredSize(new java.awt.Dimension(80, 30));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAddress.setText("Address:");

        lblPort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPort.setText("Port:");

        valuePort.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        valuePort.setText("port");

        edtPath.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        edtPath.setText("Choose a path");
        edtPath.setFocusable(false);
        edtPath.setRequestFocusEnabled(false);
        edtPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPathActionPerformed(evt);
            }
        });

        btnBrowser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBrowser.setText("Browser");
        btnBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowserActionPerformed(evt);
            }
        });

        jListName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jListName.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jListName.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListNameValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListName);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clients");
        jLabel1.setToolTipText("");

        valueHost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        valueHost.setText("address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueHost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressServer)
                        .addGap(90, 90, 90)
                        .addComponent(lblPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valuePort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(edtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrowser)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAddress)
                        .addComponent(addressServer)
                        .addComponent(lblPort)
                        .addComponent(valuePort)
                        .addComponent(valueHost))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBrowser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        Thread startServer = new Thread(new ServerHandler(PORT));
        if (btnStart.getText().equalsIgnoreCase("start")) {
            startServer.start();
            btnStart.setText("Stop");
            InetAddress localHost;
            try {
                localHost = InetAddress.getLocalHost();
                valueHost.setText(localHost.getHostAddress());
                valuePort.setText(String.valueOf(PORT));
            } catch (UnknownHostException ex) {
                Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            btnStart.setText("Start");
            startServer.interrupt();
            dispose();
            System.out.println("Server has interrupted");
            System.exit(0);
        }

    }//GEN-LAST:event_btnStartActionPerformed

    private void btnBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowserActionPerformed
        // TODO add your handling code here:
        String name = jListName.getSelectedValue();
        if (name == null) {
            JOptionPane.showMessageDialog(this, "<html><b style=\"font-size:10px;\">Please choose a client for monitoring folder changes.</b></html>");
        } else {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int result = fileChooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                String folderPath = fileChooser.getSelectedFile().getAbsolutePath();
                edtPath.setText(folderPath);
                try {
                    ServerSender serverSender = new ServerSender(Name_Socket.get(name), folderPath);
                } catch (IOException ex) {
                    Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_btnBrowserActionPerformed

    private void edtPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPathActionPerformed

    private void jListNameValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListNameValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jListNameValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressServer;
    private javax.swing.JButton btnBrowser;
    private javax.swing.JButton btnStart;
    private javax.swing.JTextField edtPath;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JList<String> jListName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblPort;
    public static javax.swing.JTable tableLogs;
    private javax.swing.JLabel valueHost;
    private javax.swing.JLabel valuePort;
    // End of variables declaration//GEN-END:variables
}
